name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          buildozer -v android debug > build.log 2>&1 || true

      - name: Mostrar arquivos gerados
        run: |
          echo "========== BIN =========="
          find . -name "*.apk"
          echo "========== AAB =========="
          find . -name "*.aab"
          echo "========== BUILD =========="
          find . -name "bin"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ControledefinancasPRO-APK
          path: |
            **/*.apk

      - name: Upload Log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log