name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-22.04

    container:
      image: kivy/buildozer:latest

    steps:

      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          buildozer -v android debug 2>&1 | tee build.log

      - name: Procurar APK
        if: always()
        run: |
          echo "===== APK ====="
          find . -name "*.apk"

          echo "===== AAB ====="
          find . -name "*.aab"

          echo "===== BIN ====="
          find . -name "bin"

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ControledefinancasPRO-APK
          path: |
            **/*.apk

      - name: Upload Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log